# Generated by Django 4.2.5 on 2023-10-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
